CREATE TABLE reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  rating TINYINT CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  approved TINYINT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  password(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

